baseURL = "http://example.org/"
# [en, zh-cn, fr, ...] determines default content language
defaultContentLanguage = "en"
# language code
languageCode = "en"
title = "hooong's  TIL"

# Change the default theme to be use when building the site with Hugo
theme = "uBlogger"

[params]
  # uBlogger theme version
  version = "1.3.X"
  [params.home.profile]
    enable = true
    # Gravatar Email for preferred avatar in home page
    gravatarEmail = ""
    # URL of avatar shown in home page
    avatarURL = "/images/avatar.jpeg"
    # title shown in home page (HTML format is supported)
    title = "홍석준 | Hong SeokJun"
    # subtitle shown in home page (HTML format is supported)
    subtitle = "BackEnd Engineer (Birdview)"
    # whether to use typeit animation for subtitle
    typeit = false
    # whether to show social links
    social = true
    # disclaimer (HTML format is supported)
    disclaimer = ""
  [params.social]
    GitHub = "hooongsj"
    Linkedin = "%EC%84%9D%EC%A4%80-%ED%99%8D-5733541b7/"
    Instagram = "hooong_sj"
    Email = "tjrwns0529@gmail.com"

[menu]
  [[menu.main]]
    identifier = "posts"
    # you can add extra information before the name (HTML format is supported), such as icons
    pre = ""
    # you can add extra information after the name (HTML format is supported), such as icons
    post = ""
    name = "Posts"
    url = "/posts/"
    # title will be shown when you hover on this menu link
    title = "hooong's  TIL"
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "Tags"
    url = "/tags/"
    title = "hooong's  TIL"
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "Categories"
    url = "/categories/"
    title = "hooong's  TIL"
    weight = 3

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration
    noClasses = false
